name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{ github.actor }} triggered Terraform Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./terraform-infra

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform-infra

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./terraform-infra

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./terraform-infra
